### ISSUE TITLE
Panel de control general

### ISSUE THREAD

**Issue by fuguet** [matudelatower/evenprom-ionic#4]
- No permite agregar empresas ni personas, revisar, los campos de texto aparecen en gris deshabilitados.

**Comment by matudelatower** [comment]
Tambien un issue de https://github.com/matudelatower/evenprom-backend

En realidad es un listado a modo de información nada mas, así estaba pensado.

Porque las personas solo se crear al loguearse con facebook o google, por mas que yo cree por atras las personas despues no van a poder loguearse.

En el caso de hacer solo el alta manual de las empresas tiempo estimado: 1 dia

**Comment by fuguet** [comment]
Perdón, no habia entendido el concepto. En ese caso PERSONAS dejarlo sin efecto, no asi empresas que si sería util que se puedan dar de alta directamente desde el panel.
Muevo el issue para seguir desde el lugar correct.
