### ISSUE TITLE
Panel de control empresas

### ISSUE THREAD

**Issue by fuguet** [matudelatower/evenprom-ionic#6]
- Activar que el desplegable se mantenga abierto al ingresar
- Al lado de NOTICIAS EVENPROM poner un cuadro igual con un texto que diga “LO AYUDAMOS A CARGAR SU EMPRESA. Llamenos por Whatsapp o escribanos que lo asistiremos gratuitamente”

PERFIL EMPRESA:
-- En Direccion empresa al final hay un boton AGREGAR, sacarlo
-- El mapa para elegir la ubicacion no carga queda en gris
- "Tu empresa es un hotel o agencia" sacarlo, ya se maneja por rubro/categoria
- Contacto empresa:
-- Aparece otro boton AGREGAR, sacarlo tambien

PUBLICACIONES DE MI EMPRESA
- Que tome por defecto el orden por ID descendente

AGREGAR LISTADO DE COMENTARIOS
- Que la empresa pueda visualizar los comentarios que le fueron realizados

**Comment by matudelatower** [comment]
esto deberia ser un issue de https://github.com/matudelatower/evenprom-backend
Tiempo estimado para la tarea: 1 dia

**Comment by fuguet** [comment]
Mi error perdon, movido
